[tool.poetry]
name = "docs"
version = "0.1.0"
description = ""
authors = ["dilipteja1 <tejadilip23898@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mkdocs = "^1.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
